### ISSUE TITLE
use Rust-CUDA to accelerate vtracer

### ISSUE THREAD

**Issue by onefish51** [etjones/vtracer_py#1]
That's really great work! 

I tested converting PNG to SVG, and the results are excellent. However, I noticed a problem: it takes a bit too long to convert a 2048*2048 image to SVG, taking about 1.005 seconds. 
```python
import time
import numpy as np
from PIL import Image

def convert_img2svg(img):
    start_time = time.time()
    
    if isinstance(img, np.ndarray):
        img = Image.fromarray(img.astype('uint8'))
    else:
        img = img.convert('RGBA')
    
    if img.mode == 'L':
        gray_pixels = list(img.getdata())
        pixels = [(value, value, value, 255) for value in gray_pixels]  # 转换为 RGBA
    else:
        img = img.convert('RGBA')
        pixels = list(img.getdata())

    print("Convert to RGBA Cost: {} s".format(time.time() - start_time))
    
    size = img.size
    svg_str = vtracer.convert_pixels_to_svg(
        pixels,
        size=size,
        colormode='binary'
    )
    print("Convert pixels to SVG Cost: {} s".format(time.time() - start_time))

    return svg_str
```
running log:
```bash
img_pil.size:  (2048, 2048)
convert RGBA Cost: 0.008136510848999023 s/img2svg
getdata Cost: 0.4795377254486084 s/img2svg
convert_pixels_to_svg Cost: 1.0046734809875488 s/img2svg
```

I need to convert a sequence of such masks to SVG, which will increase the total time significantly. Are there any acceleration solutions? 

Is it possible to use Rust-CUDA to accelerate vtracer? I haven't used Rust before; I mainly work with Python. How much effort would it take to refactor vtracer using Rust-CUDA?

Thanks!

**Comment by etjones** [comment]
I wish I could help, but that's definitely outside of my expertise. I wrote this tiny wrapper so I could use some Rust code in Python (having never written any Rust). I wouldn't have much idea how to go about bringing CUDA into the mix, too.

If you're interested in increasing speed, the original [VTracer](https://github.com/visioncortex/vtracer) authors might have more to contribute
